source 'http://rubygems.org'

gem 'eventmachine', :git => 'git://github.com/eventmachine/eventmachine.git'
gem 'em-http-request', :git => 'git://github.com/igrigorik/em-http-request.git'

gem 'yajl-ruby', :require => 'yajl'
gem 'em-stathat', '>= 0.1.0'
gem 'log4r'
